[project]
name = "module-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "psycopg2>=2.9.10",
    "pydeps>=3.0.1",
    "pylint>=3.3.7",
]
